query search_houses($only_rental:Boolean, $q:String="", $filters: HouseFiltersInput, $sort:Int, $first:Int, $skip:Int) {
  result: search_houses (only_rental: $only_rental, q: $q, filters: $filters, sort: $sort, first: $first, skip: $skip) {
    total
    items {
      id
      nm
      loc
      photo(w:800, h:800)
      photo_sub2: photo(idx:2, w:600, h:600)
      photo_sub3: photo(idx:3, w:600, h:600)
      beds
      baths
      square_feet
      price
      prop
      latlng
      status
      date
      parking
      garage
      is_in_sd
    }
  }
}
